services:
  - type: web
    name: aventurape-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://aventurape-backend.onrender.com/api/v1
      - key: VITE_BARBARA_NEXUS_URL
        value: https://barbara-nexus.onrender.com
      - key: VITE_EMAILJS_PUBLIC_KEY
        value: eCqd55MH38eEgZvfa
      - key: VITE_EMAILJS_SERVICE_ID
        value: service_w4b26t5
      - key: VITE_EMAILJS_TEMPLATE_ID
        value: template_aventurape
      - key: VITE_EMAILJS_TEMPLATE_COMMENTS_ID
        value: template_comentarios_ape
      - key: VITE_RECAPTCHA_SITE_KEY
        value: 6LfQ4CUrAAAAALzMwFCAy740fAgfLqh0OgiIK51-
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
